on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.4' # The Go version to download (if necessary) and use.
      - name: Install Ginkgo
        run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - name: Test
        run: ginkgo pkg/submitter
      - name: Build
        run: go build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            judge0-uploader
